background = #0e0c0b
foreground = #dfd0bb
cursor-color = #e97835
cursor-text = #0e0c0b
selection-background = #402312
selection-foreground = #f2e6d4

palette = 0=#080706
palette = 1=#d87363
palette = 2=#87b978
palette = 3=#f1c76a
palette = 4=#86a6b8
palette = 5=#b9899a
palette = 6=#8fb5aa
palette = 7=#dfd0bb
palette = 8=#8c7b67
palette = 9=#ef8d79
palette = 10=#a1ca91
palette = 11=#f6d890
palette = 12=#a3bdcb
palette = 13=#d0a3b0
palette = 14=#abd0c6
palette = 15=#f2e6d4
