## name: Cinderline
## author: tbenj1
background              #0e0c0b
foreground              #dfd0bb
selection_foreground    #f2e6d4
selection_background    #402312
cursor                  #e97835
cursor_text_color       #0e0c0b
active_tab_foreground   #0e0c0b
active_tab_background   #e97835
inactive_tab_foreground #dfd0bb
inactive_tab_background #1e1912

color0 #080706
color1 #d87363
color2 #87b978
color3 #f1c76a
color4 #86a6b8
color5 #b9899a
color6 #8fb5aa
color7 #dfd0bb
color8 #8c7b67
color9 #ef8d79
color10 #a1ca91
color11 #f6d890
color12 #a3bdcb
color13 #d0a3b0
color14 #abd0c6
color15 #f2e6d4
